version: "3.9"

services:
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database_ignite
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=renalt
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: gestr
    restart: always
    ports: 
      - 3000:3000
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes: 
      - .:/usr/app
    links: #links e depends_on informam as dependencias entre os containers. Como nossa aplicação depende do banco de dados subimos ele primeiro e infomamos que app é seu dependente. Links são feitos pelo nome de container.
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local